### ISSUE TITLE
Test fails

### ISSUE THREAD

**Issue by tarik02** [spekframework/spek-gradle-sample#1]
```bash
$ git clone git@github.com:spekframework/spek-gradle-sample.git
$ cd spek-gradle-sample
$ ./gradlew test
```
```
:compileKotlin UP-TO-DATE
:compileJava UP-TO-DATE
:copyMainKotlinClasses UP-TO-DATE
:processResources UP-TO-DATE
:classes UP-TO-DATE
:compileTestKotlin UP-TO-DATE
:compileTestJava UP-TO-DATE
:copyTestKotlinClasses UP-TO-DATE
:processTestResources UP-TO-DATE
:testClasses UP-TO-DATE
:junitPlatformTest
Exception in thread "main" java.lang.AbstractMethodError: Method org/jetbrains/spek/engine/Scope$Group.getType()Lorg/junit/platform/engine/TestDescriptor$Type; is abstract
        at org.jetbrains.spek.engine.Scope$Group.getType(Scope.kt)
        at org.junit.platform.launcher.TestIdentifier.from(TestIdentifier.java:60)
        at org.junit.platform.launcher.TestPlan.lambda$from$0(TestPlan.java:78)
        at org.junit.platform.engine.TestDescriptor.accept(TestDescriptor.java:245)
        at org.junit.platform.engine.TestDescriptor.lambda$accept$0(TestDescriptor.java:247)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.junit.platform.engine.TestDescriptor.accept(TestDescriptor.java:247)
        at org.junit.platform.launcher.TestPlan.lambda$from$1(TestPlan.java:79)
        at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
        at org.junit.platform.launcher.TestPlan.from(TestPlan.java:79)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:130)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:87)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.executeTests(ConsoleTestExecutor.java:65)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.lambda$execute$0(ConsoleTestExecutor.java:57)
        at org.junit.platform.console.tasks.CustomContextClassLoaderExecutor.invoke(CustomContextClassLoaderExecutor.java:33)
        at org.junit.platform.console.tasks.ConsoleTestExecutor.execute(ConsoleTestExecutor.java:57)
        at org.junit.platform.console.ConsoleLauncher.executeTests(ConsoleLauncher.java:79)
        at org.junit.platform.console.ConsoleLauncher.execute(ConsoleLauncher.java:69)
        at org.junit.platform.console.ConsoleLauncher.main(ConsoleLauncher.java:41)
:junitPlatformTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':junitPlatformTest'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 2.355 secs
```

**Comment by frankgerhardt** [comment]
Same, one year later

**Comment by vgonda** [comment]
The solution is in this issue: https://github.com/spekframework/spek/issues/195
